### ISSUE TITLE
Include secure = true when using samesite?

### ISSUE THREAD

**Issue by woeterman94** [Kurounin/ep_auth_session#5]
The iframe is working in firefox, but not in chrome.
Could it be because the same site none cookies are missing a secure flag?

![image](https://user-images.githubusercontent.com/5755057/94908365-d8e40500-04a1-11eb-8f4e-bf875bed2a6d.png)

**Comment by woeterman94** [comment]
Works
![image](https://user-images.githubusercontent.com/5755057/94908756-7a6b5680-04a2-11eb-967c-c47e69625e4f.png)
Doesn't work
![image](https://user-images.githubusercontent.com/5755057/94908863-9838bb80-04a2-11eb-8641-ed381e5c9696.png)

**Comment by Kurounin** [comment]
I published version 1.0.5 which includes the fix. Can you check if it's working fine?

**Comment by woeterman94** [comment]
Did you publish it on NPM? Or should I try locally? 
![image](https://user-images.githubusercontent.com/5755057/94917130-4303a680-04b0-11eb-8937-071770e692f2.png)

**Comment by woeterman94** [comment]
I'll try with the old version and apply the changes you did manually.

**Comment by Kurounin** [comment]
It's published on npm as version 1.0.5

**Comment by woeterman94** [comment]
```
ReferenceError: document is not defined
    at C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_auth_session\index.js:15:4
    at Layer.handle [as handle_request] (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\index.js:335:12)
    at next (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\index.js:275:10)
    at Server.handle (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\etherpad-yajsml\server.js:338:9)
    at Layer.handle [as handle_request] (C:\Users\wovd\Documents\Code\Etherpad\etherpad\node_modules\ep_etherpad-lite\node_modules\express\lib\router\layer.js:95:5)
```

**Comment by Kurounin** [comment]
Sorry about that. Try with version 1.0.6 that was just published.

**Comment by woeterman94** [comment]
Samesite is no longer set to none. 
Can you please update your other plugin that has` samesite none` in the cookies?

**Comment by Kurounin** [comment]
If I put it to samesite none, I'll have to use secure, which means that you won't be able to use the plugin without https.
Please try version 1.0.7.

**Comment by woeterman94** [comment]
No it doesn't work. 
Cookies need to be `samesite none` and `secure `when trying to iframe it from a different domain.

**Comment by Kurounin** [comment]
This is what it was supposed to have if your iframe was using https protocol. I removed the condition now so it uses `SameSite=none` and `Secure` flags always.
Try with version 1.0.8.

**Comment by woeterman94** [comment]
aaah. I didn't see your last commit! I'm so sorry. 1.0.7 is perfect.
